name: CI - User Management

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: usermanagement
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependências
        run: dotnet restore ./backend/UserManagement.API

      - name: Build
        run: dotnet build ./backend/UserManagement.API --no-restore

      - name: Instalar EF Tools
        run: dotnet tool install --global dotnet-ef

      - name: Run migrations
        run: dotnet ef database update --project ./backend/UserManagement.API
        env:
          CONNECTION_STRING: Host=localhost;Port=5432;Database=usermanagement;Username=postgres;Password=postgres

      - name: Rodar API
        run: dotnet run --project ./backend/UserManagement.API --urls=http://localhost:5205 &

      - name: Esperar API responder
        run: |
          for i in {1..20}; do
            curl -s http://localhost:5205/swagger > /dev/null && break
            echo "Aguardando API..."
            sleep 3
          done

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - name: Instalar dependências Cypress
        run: npm install
        working-directory: ./cypress

      - name: Rodar Cypress
        run: npm run cy:run
        working-directory: ./cypress
